title: Tìm hiểu về Covid-19
theme: jekyll-theme-architect
github:
  is_project_page: false
collections:
  benh-tat:
    output: true
  covid:
    output: true
  vac-xin:
    output: true
collections_dir: content
